variable "vpc_cidr" {}
variable "common_tags" {}
variable "vpc_tags" {}
variable "project_name" {}
variable "env" {}
variable "igw_tags" {}
variable "public_subnet_cidr" {}
variable "public_subnet_tags" {}
variable "private_subnet_cidr" {}
variable "private_subnet_tags" {}
variable "database_subnet_cidr" {}
variable "database_subnet_tags" {}
variable "ngw_tags" {}
variable "public_route_table_tags" {}
variable "private_route_table_tags" {}
variable "database_route_table_tags" {}
