module "vpc" {
  source                    = "./module/vpc"
  common_tags               = var.common_tags
  env                       = var.env
  project_name              = var.project_name
  vpc_cidr                  = var.vpc_cidr
  vpc_tags                  = var.vpc_tags
  igw_tags                  = var.igw_tags
  public_subnet_cidr        = var.public_subnet_cidr
  public_subnet_tags        = var.public_subnet_tags
  private_subnet_cidr       = var.private_subnet_cidr
  private_subnet_tags       = var.private_subnet_tags
  database_subnet_cidr      = var.database_subnet_cidr
  database_subnet_tags      = var.database_subnet_tags
  ngw_tags                  = var.ngw_tags
  private_route_table_tags  = var.public_route_table_tags
  public_route_table_tags   = var.private_route_table_tags
  database_route_table_tags = var.database_route_table_tags
  acceptor_vpc_id           = var.acceptor_vpc_id
  is_peering_required       = var.is_peering_required
  vpc_peering_tags          = var.vpc_peering_tags
}